### ISSUE TITLE
データーベース設計

### ISSUE THREAD

**Issue by bookmaker01** [bookmaker01/furima-32094#1]
https://gyazo.com/02ab3664e39c80bdaa8e454f1f2bc7a6

ERのURLです。

**Comment by bookmaker01** [comment]
READMEとERの確認お願いします。

**Comment by yutakatahira** [comment]
レビュー依頼ありがとうございます。

発展のissueを解消していただいた時と同様に、issueではなくプルリクエストを作成し提出しましょう。
理由としてはコードに対するコメントをさせていただきたいためです。

また、もしREADME.mdの変更内容をmasterにプッシュされている状態でしたら、ブランチを作成する前にプッシュする前の状態に戻し
ブランチにその状態を反映させるようにしましょう。

もし不明点がありましたら、コネクトにてお願いいたします。
